CREATE TABLE DEPARTMENT(
    DNO INTEGER PRIMARY KEY,
    DNAME VARCHAR(50),
    LOCATION VARCHAR(50) DEFAULT 'New Delhi'
);

CREATE TABLE EMPLOYEE(
    ENO CHAR(3) PRIMARY KEY,
    ENAME VARCHAR(50) NOT NULL,
    JOB_TYPE VARCHAR(50) NOT NULL,
    MANAGER CHAR(3),
    HIRE_DATE DATE NOT NULL,
    DNO INTEGER,
    COMMISION DECIMAL(10, 2),
    SALARY DECIMAL(7, 2) NOT NULL,
    FOREIGN KEY (MANAGER) REFERENCES EMPLOYEE(ENO),
    FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNO)
);

DESC EMPLOYEE;

DESC DEPARTMENT;